### ISSUE TITLE
Error: TypeScript: Compilation failed

### ISSUE THREAD

**Issue by lonix1** [BananaAcid/compile-superhero#6]
Repro:
- Installed extension
- Created file `file.ts` which contains this: `let foo = 123;`

Error notification:
> TypeScript: Compilation failed

Log (Window):
> [2022-05-05 07:00:00.000] [renderer1] [error] [Extension Host] Error: TypeScript: Compilation failed
	at Output.mightFinish (/home/username/.vscode/extensions/bananaacid.compile-superhero-10.3.2/node_modules/gulp-typescript/release/output.js:130:43)
	at /home/username/.vscode/extensions/bananaacid.compile-superhero-10.3.2/node_modules/gulp-typescript/release/output.js:43:22

How do I fix this?

**Comment by marchage** [comment]
... [text, delete]...

TLDR;
- <kbd>Ctrl</kbd> + <kbd>P</kbd>  
- `.vscode/extensions/bananaacid.compile-superhero-10.3.2/node_modules/gulp-typescript/release/output.js` 
- change line 130 
`this.streamFull.emit('error', new Error("TypeScript: Compilation failed"));`  
- to 
```this.streamFull.emit('error', new Error(`TypeScript: Compilation failed: ${JSON.stringify(this.result)}`));```
- restart code, 
- do what you did before, 
- see more error than before 🤞
